"""
Data Access Code Generator
Component 3 - Data Layer Migration

Generates reusable SQLAlchemy data-access functions
from safely converted SQL queries.

Only queries marked CONVERTED are emitted.
Unresolved queries are deliberately skipped.
"""

import json
import re
from pathlib import Path


def _singularize(name: str) -> str:
    """Simple deterministic table-name singularization."""

    if name.endswith("ies") and len(name) > 3:
        return name[:-3] + "y"

    if name.endswith("s") and not name.endswith("ss"):
        return name[:-1]

    return name


def _safe_identifier(value: str) -> str:
    """
    Convert a value into a valid lowercase Python-style
    identifier.
    """

    value = re.sub(
        r"[^A-Za-z0-9_]+",
        "_",
        value,
    )

    return value.strip("_").lower()


def _function_name(query: dict) -> str:
    """
    Create a deterministic function name.

    Examples:
        SELECT users -> select_users_q004
        INSERT users -> insert_user_q001
        UPDATE users -> update_user_q003
        DELETE users -> delete_user_q002
    """

    operation = query["operation"].lower()
    table = _safe_identifier(query["table"])

    if operation == "select":
        entity = table
    else:
        entity = _singularize(table)

    query_id = _safe_identifier(
        query["query_id"]
    )

    return (
        f"{operation}_{entity}_{query_id}"
    )


def _build_function(query: dict) -> str:
    """
    Generate one SQLAlchemy data-access function.
    """

    function_name = _function_name(query)

    parameters = query.get(
        "parameters",
        [],
    )

    source_file = str(
        query.get("source_file") or "unknown"
    ).replace("\\", "/")

    source_line = query.get(
        "source_line"
    )

    signature_parts = ["session"]
    signature_parts.extend(parameters)

    signature = ", ".join(
        signature_parts
    )

    sql = query["parameterized_sql"]

    parameter_lines = []

    like_wildcard_parameters = set(
        query.get("like_wildcard_parameters", [])
    )

    for parameter in parameters:
        if parameter in like_wildcard_parameters:
            value_expression = f'f"%{{{parameter}}}%"'
        else:
            value_expression = parameter

        parameter_lines.append(
            f'        "{parameter}": {value_expression},'
        )

    lines = [
        f"def {function_name}({signature}):",
        '    """',
        (
    		f"    Migrated from "
    		f"{source_file}:"
    		f"{source_line}."
	),
        (
            f"    Original query ID: "
            f"{query['query_id']}."
        ),
        '    """',
        "",
        f"    statement = text({sql!r})",
        "",
    ]

    if parameters:
        lines.extend(
            [
                "    params = {",
                *parameter_lines,
                "    }",
                "",
                (
                    "    result = session.execute("
                    "statement, params)"
                ),
            ]
        )

    else:
        lines.append(
            "    result = session.execute(statement)"
        )

    lines.append("")

    if query["operation"] == "SELECT":
        lines.append(
            "    return result.mappings().all()"
        )
    else:
        lines.extend(
            [
                "    session.commit()",
                "    return result",
            ]
        )

    return "\n".join(lines)


def generate_data_access_source(
    converted_queries: list[dict],
) -> str:
    """
    Generate complete data_access.py source code.
    """

    lines = [
        '"""',
        "Generated SQLAlchemy data-access functions.",
        "",
        (
            "Generated by Component 3 - "
            "Data Layer Migration."
        ),
        "",
        (
            "Dynamic legacy values are passed using "
            "SQLAlchemy named bind parameters."
        ),
        '"""',
        "",
        "from sqlalchemy import text",
        "",
        "",
    ]

    converted = [
        query
        for query in converted_queries
        if query.get("status") == "CONVERTED"
    ]

    for index, query in enumerate(converted):
        lines.append(
            _build_function(query)
        )

        if index < len(converted) - 1:
            lines.extend(
                [
                    "",
                    "",
                ]
            )

    lines.append("")

    return "\n".join(lines)


def load_converted_queries(
    input_file: str | Path,
) -> list[dict]:
    """Load converted_queries.json."""

    input_path = Path(input_file)

    return json.loads(
        input_path.read_text(
            encoding="utf-8"
        )
    )


def generate_data_access(
    input_file: str | Path,
    output_file: str | Path,
) -> None:
    """
    Generate data_access.py from converted query IR.
    """

    converted_queries = (
        load_converted_queries(
            input_file
        )
    )

    source = generate_data_access_source(
        converted_queries
    )

    output_path = Path(output_file)

    output_path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    output_path.write_text(
        source,
        encoding="utf-8",
    )
