"""
Generated SQLAlchemy data-access functions.

Generated by Component 3 - Data Layer Migration.

Dynamic legacy values are passed using SQLAlchemy named bind parameters.
"""

from sqlalchemy import text


def select_users_q001(session, q):
    """
    Migrated from C:/Users/sanjula/Desktop/Research/Automated_Modernization_of_Legacy_Procedural_PHP_Web_Applications/benchmarks/apps/hard_crud/legacy/01_like_search.php:9.
    Original query ID: Q001.
    """

    statement = text('SELECT id, name, email FROM users WHERE name LIKE :q')

    params = {
        "q": f"%{q}%",
    }

    result = session.execute(statement, params)

    return result.mappings().all()
