"""
Generated SQLAlchemy ORM models.

Generated by Component 3 - Data Layer Migration.
"""

from sqlalchemy import (
    BigInteger,
    Boolean,
    Date,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    LargeBinary,
    Numeric,
    SmallInteger,
    String,
    Text,
    Time,
)
from sqlalchemy.orm import DeclarativeBase, mapped_column, relationship


class Base(DeclarativeBase):
    pass


class User(Base):
    __tablename__ = "users"

    id = mapped_column(Integer, primary_key=True, autoincrement=True, nullable=False)
    name = mapped_column(String(100), nullable=False)
    email = mapped_column(String(150), nullable=False)
    status = mapped_column(String(20), nullable=False)
    role = mapped_column(String(30), nullable=False)
    created_at = mapped_column(DateTime, nullable=False)

    orders = relationship("Order", back_populates="user")


class Category(Base):
    __tablename__ = "categories"

    id = mapped_column(Integer, primary_key=True, autoincrement=True, nullable=False)
    name = mapped_column(String(100), nullable=False)

    products = relationship("Product", back_populates="category")


class Product(Base):
    __tablename__ = "products"

    id = mapped_column(Integer, primary_key=True, autoincrement=True, nullable=False)
    category_id = mapped_column(Integer, ForeignKey("categories.id"), nullable=False)
    title = mapped_column(String(150), nullable=False)
    description = mapped_column(Text, nullable=True)
    price = mapped_column(Numeric(10, 2), nullable=False)
    stock = mapped_column(Integer, nullable=False)
    status = mapped_column(String(20), nullable=False)

    category = relationship("Category", back_populates="products")
    order_items = relationship("OrderItem", back_populates="product")


class Order(Base):
    __tablename__ = "orders"

    id = mapped_column(Integer, primary_key=True, autoincrement=True, nullable=False)
    user_id = mapped_column(Integer, ForeignKey("users.id"), nullable=False)
    total = mapped_column(Numeric(10, 2), nullable=False)
    status = mapped_column(String(20), nullable=False)
    created_at = mapped_column(DateTime, nullable=False)

    user = relationship("User", back_populates="orders")
    order_items = relationship("OrderItem", back_populates="order")


class OrderItem(Base):
    __tablename__ = "order_items"

    id = mapped_column(Integer, primary_key=True, autoincrement=True, nullable=False)
    order_id = mapped_column(Integer, ForeignKey("orders.id"), nullable=False)
    product_id = mapped_column(Integer, ForeignKey("products.id"), nullable=False)
    quantity = mapped_column(Integer, nullable=False)
    unit_price = mapped_column(Numeric(10, 2), nullable=False)

    order = relationship("Order", back_populates="order_items")
    product = relationship("Product", back_populates="order_items")
