"""
Generated SQLAlchemy data-access functions.

Generated by Component 3 - Data Layer Migration.

Dynamic legacy values are passed using SQLAlchemy named bind parameters.
"""

from sqlalchemy import text


def insert_user_q001(session, name, email):
    """
    Migrated from ../../benchmarks/apps/simple_crud/legacy/create_user.php:9.
    Original query ID: Q001.
    """

    statement = text("INSERT INTO users (name, email, status) VALUES (:name, :email, 'active')")

    params = {
        "name": name,
        "email": email,
    }

    result = session.execute(statement, params)

    session.commit()
    return result


def delete_user_q002(session, id):
    """
    Migrated from ../../benchmarks/apps/simple_crud/legacy/delete_user.php:8.
    Original query ID: Q002.
    """

    statement = text('DELETE FROM users WHERE id = :id')

    params = {
        "id": id,
    }

    result = session.execute(statement, params)

    session.commit()
    return result


def update_user_q003(session, name, id):
    """
    Migrated from ../../benchmarks/apps/simple_crud/legacy/update_user.php:8.
    Original query ID: Q003.
    """

    statement = text('UPDATE users SET name = :name WHERE id = :id')

    params = {
        "name": name,
        "id": id,
    }

    result = session.execute(statement, params)

    session.commit()
    return result


def select_users_q004(session):
    """
    Migrated from ../../benchmarks/apps/simple_crud/legacy/users.php:4.
    Original query ID: Q004.
    """

    statement = text('SELECT id, name, email, status FROM users')

    result = session.execute(statement)

    return result.mappings().all()
