"""
Generated SQLAlchemy ORM models.

Generated by Component 3 - Data Layer Migration.
"""

from sqlalchemy import (
    BigInteger,
    Boolean,
    Date,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    LargeBinary,
    Numeric,
    SmallInteger,
    String,
    Text,
    Time,
)
from sqlalchemy.orm import DeclarativeBase, mapped_column, relationship


class Base(DeclarativeBase):
    pass


class User(Base):
    __tablename__ = "users"

    id = mapped_column(Integer, primary_key=True, autoincrement=True, nullable=False)
    name = mapped_column(String(100), nullable=False)
    email = mapped_column(String(150), nullable=False)
    status = mapped_column(String(20), nullable=False)

    appointments = relationship("Appointment", back_populates="user")


class Appointment(Base):
    __tablename__ = "appointments"

    id = mapped_column(Integer, primary_key=True, autoincrement=True, nullable=False)
    user_id = mapped_column(Integer, ForeignKey("users.id"), nullable=False)
    appointment_date = mapped_column(Date, nullable=False)
    status = mapped_column(String(20), nullable=True)

    user = relationship("User", back_populates="appointments")
