"""
Generated SQLAlchemy data-access functions.

Generated by Component 3 - Data Layer Migration.

Dynamic legacy values are passed using SQLAlchemy named bind parameters.
"""

from sqlalchemy import text


def select_products_q001(session):
    """
    Migrated from C:/Users/sanjula/Desktop/Research/Automated_Modernization_of_Legacy_Procedural_PHP_Web_Applications/benchmarks/apps/mixed_crud/legacy/01_select.php:4.
    Original query ID: Q001.
    """

    statement = text('SELECT id, title, price FROM products')

    result = session.execute(statement)

    return result.mappings().all()


def select_products_q002(session, id):
    """
    Migrated from C:/Users/sanjula/Desktop/Research/Automated_Modernization_of_Legacy_Procedural_PHP_Web_Applications/benchmarks/apps/mixed_crud/legacy/02_interpolation.php:7.
    Original query ID: Q002.
    """

    statement = text('SELECT id, title, price FROM products WHERE id = :id')

    params = {
        "id": id,
    }

    result = session.execute(statement, params)

    return result.mappings().all()


def delete_product_q003(session, id):
    """
    Migrated from C:/Users/sanjula/Desktop/Research/Automated_Modernization_of_Legacy_Procedural_PHP_Web_Applications/benchmarks/apps/mixed_crud/legacy/03_concat.php:8.
    Original query ID: Q003.
    """

    statement = text('DELETE FROM products WHERE id = :id')

    params = {
        "id": id,
    }

    result = session.execute(statement, params)

    session.commit()
    return result


def select_products_q004(session):
    """
    Migrated from C:/Users/sanjula/Desktop/Research/Automated_Modernization_of_Legacy_Procedural_PHP_Web_Applications/benchmarks/apps/mixed_crud/legacy/04_reassignment.php:7.
    Original query ID: Q004.
    """

    statement = text('SELECT id, title, price FROM products')

    result = session.execute(statement)

    return result.mappings().all()


def update_product_q005(session, title, price, id):
    """
    Migrated from C:/Users/sanjula/Desktop/Research/Automated_Modernization_of_Legacy_Procedural_PHP_Web_Applications/benchmarks/apps/mixed_crud/legacy/05_update.php:11.
    Original query ID: Q005.
    """

    statement = text('UPDATE products SET title = :title, price = :price WHERE id = :id')

    params = {
        "title": title,
        "price": price,
        "id": id,
    }

    result = session.execute(statement, params)

    session.commit()
    return result
