"""
Generated SQLAlchemy ORM models.

Generated by Component 3 - Data Layer Migration.
"""

from sqlalchemy import (
    BigInteger,
    Boolean,
    Date,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    LargeBinary,
    Numeric,
    SmallInteger,
    String,
    Text,
    Time,
)
from sqlalchemy.orm import DeclarativeBase, mapped_column, relationship


class Base(DeclarativeBase):
    pass


class Product(Base):
    __tablename__ = "products"

    id = mapped_column(Integer, primary_key=True, autoincrement=True, nullable=False)
    title = mapped_column(String(255), nullable=False)
    price = mapped_column(Numeric(10, 2), nullable=False)
